spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat_assistant_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate  # Use Flyway for schema management
    properties:
      hibernate:
        format_sql: true

# Logging for Development
logging:
  level:
    com.krd.chatassistant: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.ai: DEBUG
